name: CI
on:

  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main

  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  generic:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          cache: true

      - name: Configure CMake
        shell: bash
        run: pixi run -e default prebuild

      - name: Build & Install
        shell: bash
        run: |
          pixi run -e default build
          pixi run -e default install

      - name: Run C++ Test
        shell: bash
        run: pixi run -e default ctest

      - name: Run Python Test
        shell: bash
        run: pixi run -e default pytest


  emscripten_wasm:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.73"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          cache: true

      - name: Prepare WASM host
        shell: bash
        run: pixi install -e wasm-host

      - name: Configure
        shell: bash
        run: pixi run -e wasm-build prebuild

      - name: Build
        shell: bash
        run: pixi run -e wasm-build build

      - name: Install
        shell: bash
        run: pixi run -e wasm-build install
